#! /bin/sh

CBR='%{B-}'         # reset bg color
CB1='%{B#FFfdf6e3}' # blue
CB2='%{B#FF839496}' # off white

CFR='%{F#FF839496}'         # reset fg color
CF1='%{F#FF002b36}' # dark gray
CF2='%{F#FFfdf6e3}' # blue
CF3='%{F#FF839496}' # violet
CF4='%{F#FF839496}' # off white

RA='%{r}'           # right align
AC='%{A:'           # start click area
AB=':}'             # end click area cmd
AE='%{A}'           # end click area

LT='T'              # tiled layout
LM="M"              # monocle layout

DO='+'              # occupied desktop
DF='-'              # free 839496p⮀

goto='bspc desktop -f'       # go to this desktop
cycle='bspc desktop -l next' # cycle tiled/monocle

logo="${CB1}${CF1}${AC}~/.config/bspwm/panel/scripts/spawn_dmenu${AB} $(hostname -s) ${CB2}${CF2}⮀${AE}"

while read -r line ; do
	case $line in
	S*)
		sys_infos="${RA}${line#?}"
	;;
	T*)
		title="${CF3} ${line#?} "
	;;
	W*)
		wm_infos="${CB2}"
		IFS=':'
		set -- ${line#?}
		while [ $# -gt 0 ] ; do
			item=$1
			name=${item#?}
			case $item in
			O*) wm_infos="${wm_infos}${CF2}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # active occupied desktop
			F*) wm_infos="${wm_infos}${CF2}${AC}${goto} ${name}${AB} ${DF} ${AE}";; # active free desktop
			U*) wm_infos="${wm_infos}${CF3}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # active urgent desktop
			o*) wm_infos="${wm_infos}${CF1}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # inactive occupied desktop
			f*) wm_infos="${wm_infos}${CF1}${AC}${goto} ${name}${AB} ${DF} ${AE}";; # inactive free desktop
			u*) wm_infos="${wm_infos}${CF3}${AC}${goto} ${name}${AB} ${DO} ${AE}";; # inactive urgent desktop
			L*)
				# layout
				case $name in
				t*) # tiled
					layout=${LT}
				;;
				f*) # monocle
					layout=${LM}
				;;
				esac
				wm_infos="${wm_infos} ${CF1}${AC}${cycle}${AB}${layout}${AE} ${CBR}${CF4}⮀"
			;;
			esac
			shift
		done
	;;
	esac
	printf "%s\n" "$logo $wm_infos $title $sys_infos"
done
