#!/bin/bash

# For reloading bspwm
if [ -e "$BSPWM_TREE" ] ; then
    bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
    rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

PANEL_FIFO=/tmp/panel_fifo

bspc config border_width		5
bspc config window_gap			5
bspc config top_padding			13
bspc config bottom_padding		-2
bspc config left_padding		-2
bspc config right_padding		-2
bspc config split_ratio			0.50
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config focus_follows_pointer	true
bspc config auto_alternate		true
bspc config auto_cancel			true
bspc config history_aware_focus		true
bspc config focused_border_color	'#66d9ef'
bspc config urgent_border_color		'#f92672'
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a Chromium desktop=^1
bspc rule -a Google-chrome-stable desktop=^1
bspc rule -a crx_nckgahadagoaajjgafhacjanaoiihapd floating=true
bspc rule -a Skype floating=on desktop=^10

rm -f $PANEL_FIFO
mkfifo $PANEL_FIFO

xsetroot -cursor_name left_ptr

$HOME/.config/bspwm/panel/panel &
