#!/bin/sh

# Figure out current screen size
SCREENWIDTH=$(xrandr -q | grep Screen | awk '{print $8}')
SCREENHEIGHT=$(xrandr -q | grep Screen | awk '{print $10}' | sed s/,//)

# How close to the screen edges do we begin/end?
EDGEWIDTH=50
DMENUWIDTH=$(($SCREENWIDTH - $(($EDGEWIDTH + $EDGEWIDTH))))

# dmenu X/Y coordinates
XPOS=$EDGEWIDTH
YPOS=$(($(($SCREENHEIGHT / 2)) - 15))

FGSELECT="#A3A6AB"
BGSELECT="#f93254"
FG="#fdf6e3"
BG="#22313F"
FONT="-*-terminus-*-*-*-*-*-*-*-*-*-*-*-*"

dmenu_run -w $DMENUWIDTH -x $XPOS -y $YPOS -fn ${FONT} -nb $BG -nf $FG -sb $BGSELECT -p "%"
-dim 0.75
#dmenu_run -o 0.8 -fn ${FONT} -h 25 -w 500 -x 680 -y 490 -nb $BG -nf $FG -sb $BGSELECT -p "%"
