#!/bin/sh

pkill -x dmenu
xdotool search --class conky windowunmap %@
dmenu_run -l 20 \
	-w 205 \
	-y 0 \
	-x 60 \
	-fn -lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1 \
	-nb '#ffffff' \
	-nf '#383830' \
	-sf '#383830' \
	-sb '#66d9ef' \
	-o 0.98 2>/dev/null
